baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/events'
weight = 10

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
